name: Build and push package to GitHub

on:
  release:
    types: [ published ]

jobs:
  create-package:
    name: Create package and push to private repo
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install .NET tools
        run: dotnet tool restore

      - name: Update project files with GitVersion
        run: dotnet tool run dotnet-gitversion /updateprojectfiles
    
      - name: Configure GitHub package source
        run: dotnet nuget add source --username Smalls1652 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Smalls1652/index.json"

      - name: Restore dependencies
        run: dotnet restore

      - name: Create .nupkg
        run: dotnet pack --configuration Release --no-restore

      - name: Push to package registry
        run: dotnet nuget push "./artifacts/package/release/*.nupkg" --source github --api-key ${{ secrets.GITHUB_TOKEN }}
